# Generated by Django 5.0.6 on 2024-07-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_user_alter_paymentinfo_nombre_titular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
